apiVersion: apps/v1
kind: Deployment
metadata:
  name: bla
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: whateverrr
          image: nginx:stable
          
